services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web-forms
    ports:
      - "5173:5173"
    volumes:
      - ./web-forms:/app
      - /app/node_modules
    tty: true
    stdin_open: true
  # n8n:
  #   image: n8nio/n8n
  #   ports:
  #     - "5678:5678"
  #   volumes:
  #     - n8n_data:/home/node/.n8n
  #   environment:
  #     - N8N_BASIC_AUTH_ACTIVE=true
  #     - N8N_BASIC_AUTH_USER=admin
  #     - N8N_BASIC_AUTH_PASSWORD=admin
  #     - N8N_SECURE_COOKIE=false
  gotenberg:
    image: gotenberg/gotenberg:8
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: system
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./backend/db/migrations/create_tarefas.sql:/docker-entrypoint-initdb.d/create_tarefas.sql:ro
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8090:8090"
    volumes:
      - ./backend:/backend
    working_dir: /backend
    depends_on:
      - db
volumes:
  pgdata:
  # ADIÇÃO: O volume para o n8n precisa ser declarado aqui.
  n8n_data:
  # REMOÇÃO: hapipgdata foi removido pois não estava sendo utilizado.
